# Generated by Django 2.0.4 on 2018-11-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181113_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventuser',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='eventuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='sub_title',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='users.Event'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub',
            field=models.ManyToManyField(blank=True, null=True, to='users.SubTitle'),
        ),
        migrations.DeleteModel(
            name='EventUser',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
