# Generated by Django 2.0.4 on 2018-11-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_trial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='inner_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
