# Generated by Django 2.0.4 on 2018-11-23 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_trial_inner_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trial',
            name='inner_html',
        ),
    ]
